# Generated by Django 3.0.7 on 2020-06-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quillpost',
            options={'ordering': ['-pk']},
        ),
    ]
